### ISSUE TITLE
Conflict issue

### ISSUE THREAD

**Issue by DanGthatRokGallery** [stevenbenner/jquery-powertip#151] opened 2016-11-02 16:20 UTC
I realize this isn't your issue - I just wanted to say of the tooltip packages I've tried in Github this is my favourite.
Unfortunately I can't use it as my project uses RSDirectory! from RSJoomla which uses a hard coded jquery 1.7.12 version :(

I've tried placing the 1.9.1 everywhere in the HTML but it always breaks the Google Map coding of RSDirectory!

However I will definitely be using it in other projects 👍

**Comment by stevenbenner** [comment] 2016-12-05 02:14
PowerTip is compatible with jQuery 1.7.0 or later, so you shouldn't even need to add jQuery 1.9.1 to get PowerTip working.

If you're having problems with PowerTip when using jQuery 1.7.12 then it's probably a bug. Could you let me know what's going wrong with PowerTip in this case?

**Comment by stevenbenner** [comment] 2017-01-22 16:29
Closing this issue since there has been no reply for a while. Please comment here if you can reproduce the problem and give me more information in the future.

**Closed by stevenbenner** 2017-01-22 16:29 UTC
