### ISSUE TITLE
in IOS tooltip prevent default click event

### ISSUE THREAD

**Issue by aneeshsudhakaran** [stevenbenner/jquery-powertip#167] opened 2018-02-01 13:35 UTC
```
<a class="swatchanchor instock tool-tip" href="http://devriation.com?pid=lola-check-dress-26786&amp;dwvar_lola-check-dress-26786_size=M&amp;dwvar_lola-check-dress-26786_color=Green%2fMulti&amp;source=pdp" data-placement="s">
<span>M</span>
</a>
```

```
$('.tool-tip').each(function( index ) {
				  var p =$(this).data('placement');
				  $(this).powerTip({ placement: p  , smartPlacement: true });  
			});
```

when i take this in IOS 7, its need double touch for get the link active. 

Thanks in advance!

**Comment by stevenbenner** [comment] 2018-02-26 02:48
I can't reproduce this issue on my Android device. Unfortunately I do not have an iOS device to test on at the moment.

The PowerTip code does not prevent event bubbling, so the expected behavior for a link on a tap would be to open the tooltip (because focus was received) and let the browser navigate to the link target.

Can you go to the [PowerTip project page](https://stevenbenner.github.io/jquery-powertip/) (e.g. the "MIT license" link) and see if you get the same behavior when tapping on any of the links in the footer at the very bottom of the page?

**Comment by stevenbenner** [comment] 2018-04-15 13:37
I'm going to close this issue because there hasn't been a response for some time. Please reply back if you can do the test I requested or have more information and I'll reopen the issue.

**Closed by stevenbenner** 2018-04-15 13:37 UTC
