### ISSUE TITLE
clicking inside powertip closing the powertip

### ISSUE THREAD

**Issue by giswebmaster** [stevenbenner/jquery-powertip#124] opened 2014-11-04 16:59 UTC
I am having a problem with an imagemap I have placed inside a powertip module.  whenever I click it, the powertip closes.  this does not occur when clicking any other links inside the window.  the only difference is this href is pointing to a javascript function that subsequently calls other functions which should update another <div> inside the powertip.  is there a way to prevent powertip from closing when this happens or is this another bug?

**Comment by stevenbenner** [comment] 2017-01-22 16:31
Closing this issue because there has been no additional information given for some time. Please comment here if you can reproduce the problem and give me information or an example to help me diagnose it in the future.

**Closed by stevenbenner** 2017-01-22 16:31 UTC
