### ISSUE TITLE
followMouse weird positioning after switching tabs

### ISSUE THREAD

**Issue by eolant** [stevenbenner/jquery-powertip#147] opened 2016-05-03 05:11 UTC
If I set followMouse and apply tooltip to a focusable element then after switching active tab and returning tooltip appears outside of the element and continues to follow the mouse.
https://jsfiddle.net/s4djhwwg/

**Comment by eolant** [comment] 2016-05-04 03:06
Removing focus event binding seems fixes the problem, but generally I think when you change positioning of the tooltip you have to check you actually over the target element.

**Comment by maxw3st** [comment] 2016-05-04 07:26
bind followMouse to a specific/intended element—only when that element has
focus

On Tue, May 3, 2016 at 11:06 PM, Vitaly <notifications@github.com> wrote:

> Removing focus event binding seems fixes the problem, but generally I
> think when you change positioning of the tooltip you have to check you
> actually over the target element.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenbenner/jquery-powertip/issues/147#issuecomment-216731178>
>



-- 
Max West

**Comment by stevenbenner** [comment] 2016-05-07 17:47
Thanks for the bug report and very helpful JSFiddle example! I can't seem to reproduce exactly what you're seeing, but I can get it to behave weird by focusing it.

What OS and browser(s) are you using? And what are the steps to reproduce this. Are you switching tabs via keyboard shortcuts or with your mouse? Do you click the link before switching tabs, or do you just mouse over it and immediately switch the tab? Do you focus via tabbing or clicking?

You're probably right that followMouse should not bind focus events, and should probably verify that the mouse is actually over the element. But I'd like to see exactly what you're seeing before trying to fix it.

**Comment by eolant** [comment] 2016-05-07 22:20
It's happening in Firefox and Chrome on Mac and Windows. Steps to reproduce:
1. Click on the link
2. Click on another tab in the browser
3. Click on tab with fiddle and you'll be able to see how tooltip positioned underneath empty space and follows the mouse.

In my case it wasn't a link but it was SVG group. In order to fix that I have removed focus binding from the source code and it seems solved the problem.

**Comment by stevenbenner** [comment] 2016-05-07 22:38
Thanks! Got it. I can reproduce this by focusing the element, switching another browser tab, then switching back to the original tab.

It looks like binding to focus in this case is the cause of the problem. When switching back to the original tab the browser is firing the focus event again, causing the tooltip to reappear without any mouse cursor info. I can easily solve this by not binding to the focus event when `followMouse` is `true`. But just removing that event binding would reduce the accessibility of the tooltips for users who navigate with the keyboard.

I'll try to come up with a solution that will work everyone. Maybe mouse location tracking and/or some special handing of the focus event in this scenario.

**Comment by eolant** [comment] 2016-05-07 22:52
Awesome, thanks :)

**Comment by stevenbenner** [comment] 2017-07-16 13:35
Fixed in commit 3c1d8434a5a53233b1d6d03954edd9094deeb9af. This change will be released with the next version of PowerTip.

**Closed** 2017-07-16 13:35 UTC
Labels: Bug
