### ISSUE TITLE
Apply powertip to dynamically created elements?

### ISSUE THREAD

**Issue by seabasss** [stevenbenner/jquery-powertip#179] opened 2019-11-24 04:26 UTC
Hi,

Is it possible to apply powertip to all elements with the powertip class: already created elements or dynamically created ones? Something similar to:

```
$(document).powerTip('.tooltip', {});
```
or

```
$(document).on('mouseover', '.tooltip', function(e) {
  $(this).powertip({});
});
```

**Comment by seabasss** [comment] 2020-02-10 18:09
Any ideas for this? Thanks!

**Comment by stevenbenner** [comment] 2022-02-20 15:19
This feature has been on the to-do list for a very long time. See issue #33.

There are a couple workarounds in the discussion for that issue, but live mode (a.k.a. event delegation) is still not something that PowerTip supports. So for now there isn't a built-in way.

Closing this issue as a duplicate of #33.

**Closed** 2022-02-20 15:19 UTC
Labels: Feature
